version: "3"

services:
  dremio: 
    image: dremio/dremio-oss:latest
    container_name: dremio-oss
    ports:
      - "9047:9047"
      - "31010:31010"
      - "45678:45678"
    volumes:
      - ./data:/opt/dremio/data
  